# Generated by Django 3.1.5 on 2021-01-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('wrong_tries', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
